# Generated by Django 6.0.3 on 2026-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_name", models.CharField(max_length=255, unique=True)),
                ("policy_number", models.CharField(max_length=255, unique=True)),
                ("policy_type", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
