# Generated by Django 6.0.3 on 2026-03-13 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0003_modern"),
    ]

    operations = [
        migrations.AddField(
            model_name="modern",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="modern",
            name="updated_at",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
