# Generated by Django 6.0.3 on 2026-03-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0004_modern_created_at_modern_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Modern",
        ),
    ]
