# Generated by Django 6.0.3 on 2026-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0005_delete_modern"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceGroupOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_owner", models.CharField(max_length=255)),
                ("term_year", models.CharField(max_length=255)),
                ("groups", models.ManyToManyField(to="insurance.insurance")),
            ],
        ),
    ]
