# Generated by Django 6.0.3 on 2026-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0006_insurancegroupowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("publications", models.ManyToManyField(to="insurance.publication")),
            ],
            options={
                "ordering": ["headline"],
            },
        ),
        migrations.DeleteModel(
            name="InsuranceGroupOwner",
        ),
    ]
