apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
        - name: django-api
          image: cyborden/cicd-sample:e223a19
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "bpims" # Ensure these match your actual DB settings
            - name: POSTGRES_USER
              value: "bpims"
            - name: POSTGRES_PASSWORD
              value: "bpims"
