apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
        - name: django-api
          image: cyborden/bpims-django-api:v1
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: POSTGRES_HOST
              value: postgres-service