apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: default
  labels:
    app: django-api
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
        - name: django-api
          image: cyborden/cicd-sample:79bdd2c
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: "100Mi"
              cpu: 0.5
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "bpims"
            - name: POSTGRES_USER
              value: "bpims"
            - name: POSTGRES_PASSWORD
              value: "bpims"
      automountServiceAccountToken: false
